name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.5' # Replace with your Go version

    - name: Install dependencies
      run: go mod tidy

    - name: Build binaries
      run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/todo-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o dist/todo-darwin-amd64
          GOOS=windows GOARCH=amd64 go build -o dist/todo-windows-amd64.exe

    - name: Get Latest Commit Info
      id: commit_info
      run: |
        echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "COMMIT_MESSAGE=$(git log -1 --pretty=format:'%s')" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.COMMIT_SHA }}
        release_name: Release ${{ env.COMMIT_SHA }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Linux Binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/todo-linux-amd64
        asset_name: todo-linux-amd64
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload macOS Binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/todo-darwin-amd64
        asset_name: todo-darwin-amd64
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Windows Binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/todo-windows-amd64.exe
        asset_name: todo-windows-amd64.exe
        asset_content_type: application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

